# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import inference_pb2 as inference__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in inference_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FaceInferenceStub(object):
    """Face detection and recognition inference service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DetectFaces = channel.unary_unary(
                '/facelock.inference.FaceInference/DetectFaces',
                request_serializer=inference__pb2.DetectRequest.SerializeToString,
                response_deserializer=inference__pb2.DetectResponse.FromString,
                _registered_method=True)
        self.ExtractEmbedding = channel.unary_unary(
                '/facelock.inference.FaceInference/ExtractEmbedding',
                request_serializer=inference__pb2.EmbeddingRequest.SerializeToString,
                response_deserializer=inference__pb2.EmbeddingResponse.FromString,
                _registered_method=True)
        self.CheckLiveness = channel.unary_unary(
                '/facelock.inference.FaceInference/CheckLiveness',
                request_serializer=inference__pb2.LivenessRequest.SerializeToString,
                response_deserializer=inference__pb2.LivenessResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/facelock.inference.FaceInference/Health',
                request_serializer=inference__pb2.HealthRequest.SerializeToString,
                response_deserializer=inference__pb2.HealthResponse.FromString,
                _registered_method=True)


class FaceInferenceServicer(object):
    """Face detection and recognition inference service
    """

    def DetectFaces(self, request, context):
        """Detect faces in an image and return bounding boxes with landmarks
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExtractEmbedding(self, request, context):
        """Extract face embedding from aligned face image
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckLiveness(self, request, context):
        """Check if face is real (liveness detection)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Health check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FaceInferenceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DetectFaces': grpc.unary_unary_rpc_method_handler(
                    servicer.DetectFaces,
                    request_deserializer=inference__pb2.DetectRequest.FromString,
                    response_serializer=inference__pb2.DetectResponse.SerializeToString,
            ),
            'ExtractEmbedding': grpc.unary_unary_rpc_method_handler(
                    servicer.ExtractEmbedding,
                    request_deserializer=inference__pb2.EmbeddingRequest.FromString,
                    response_serializer=inference__pb2.EmbeddingResponse.SerializeToString,
            ),
            'CheckLiveness': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckLiveness,
                    request_deserializer=inference__pb2.LivenessRequest.FromString,
                    response_serializer=inference__pb2.LivenessResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=inference__pb2.HealthRequest.FromString,
                    response_serializer=inference__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'facelock.inference.FaceInference', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('facelock.inference.FaceInference', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FaceInference(object):
    """Face detection and recognition inference service
    """

    @staticmethod
    def DetectFaces(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/facelock.inference.FaceInference/DetectFaces',
            inference__pb2.DetectRequest.SerializeToString,
            inference__pb2.DetectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExtractEmbedding(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/facelock.inference.FaceInference/ExtractEmbedding',
            inference__pb2.EmbeddingRequest.SerializeToString,
            inference__pb2.EmbeddingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckLiveness(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/facelock.inference.FaceInference/CheckLiveness',
            inference__pb2.LivenessRequest.SerializeToString,
            inference__pb2.LivenessResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/facelock.inference.FaceInference/Health',
            inference__pb2.HealthRequest.SerializeToString,
            inference__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
