// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function EventsEmit(eventName, ...data) {
  return window.runtime.EventsEmit(eventName, ...data);
}

export function EventsOn(eventName, callback) {
  return window.runtime.EventsOn(eventName, callback);
}

export function EventsOnce(eventName, callback) {
  return window.runtime.EventsOnce(eventName, callback);
}

export function EventsOnMultiple(eventName, callback, maxCallbacks) {
  return window.runtime.EventsOnMultiple(eventName, callback, maxCallbacks);
}

export function EventsOff(eventName, ...additionalEventNames) {
  return window.runtime.EventsOff(eventName, ...additionalEventNames);
}

export function LogDebug(message) {
  return window.runtime.LogDebug(message);
}

export function LogInfo(message) {
  return window.runtime.LogInfo(message);
}

export function LogWarning(message) {
  return window.runtime.LogWarning(message);
}

export function LogError(message) {
  return window.runtime.LogError(message);
}

export function LogFatal(message) {
  return window.runtime.LogFatal(message);
}

export function WindowReload() {
  return window.runtime.WindowReload();
}

export function WindowSetTitle(title) {
  return window.runtime.WindowSetTitle(title);
}

export function WindowFullscreen() {
  return window.runtime.WindowFullscreen();
}

export function WindowUnfullscreen() {
  return window.runtime.WindowUnfullscreen();
}

export function WindowMinimise() {
  return window.runtime.WindowMinimise();
}

export function WindowUnminimise() {
  return window.runtime.WindowUnminimise();
}

export function WindowMaximise() {
  return window.runtime.WindowMaximise();
}

export function WindowToggleMaximise() {
  return window.runtime.WindowToggleMaximise();
}

export function WindowUnmaximise() {
  return window.runtime.WindowUnmaximise();
}

export function WindowCenter() {
  return window.runtime.WindowCenter();
}

export function Quit() {
  return window.runtime.Quit();
}
