// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelEnrollment() {
  return window['go']['main']['App']['CancelEnrollment']();
}

export function ControlService(arg1) {
  return window['go']['main']['App']['ControlService'](arg1);
}

export function DeleteUser(arg1) {
  return window['go']['main']['App']['DeleteUser'](arg1);
}

export function DownloadLogs() {
  return window['go']['main']['App']['DownloadLogs']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetEnrollmentStatus() {
  return window['go']['main']['App']['GetEnrollmentStatus']();
}

export function GetLogs(arg1) {
  return window['go']['main']['App']['GetLogs'](arg1);
}

export function GetPAMServices() {
  return window['go']['main']['App']['GetPAMServices']();
}

export function GetPAMStatus() {
  return window['go']['main']['App']['GetPAMStatus']();
}

export function GetServiceStatus() {
  return window['go']['main']['App']['GetServiceStatus']();
}

export function GetUsers() {
  return window['go']['main']['App']['GetUsers']();
}

export function PAMAction(arg1, arg2) {
  return window['go']['main']['App']['PAMAction'](arg1, arg2);
}

export function PAMToggle(arg1) {
  return window['go']['main']['App']['PAMToggle'](arg1);
}

export function RunAuthTest() {
  return window['go']['main']['App']['RunAuthTest']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function StartCamera() {
  return window['go']['main']['App']['StartCamera']();
}

export function StartCameraStream() {
  return window['go']['main']['App']['StartCameraStream']();
}

export function StartEnrollment(arg1) {
  return window['go']['main']['App']['StartEnrollment'](arg1);
}

export function StopCamera() {
  return window['go']['main']['App']['StopCamera']();
}

export function StopCameraStream() {
  return window['go']['main']['App']['StopCameraStream']();
}
