// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface UserResponse {
  username: string;
  samples: number;
  active: boolean;
}

export interface EnrollmentStatus {
  is_enrolling: boolean;
  username: string;
  progress: number;
  total: number;
  message: string;
}

export interface AuthTestResult {
  success: boolean;
  error?: string;
  user?: string;
  confidence?: number;
  processing_time?: string;
  liveness_passed: boolean;
  challenge_description?: string;
  image_data?: string;
  image_width?: number;
  image_height?: number;
  bounding_boxes?: Array<{
    x: number;
    y: number;
    width: number;
    height: number;
    confidence: number;
  }>;
  faces_detected: number;
}

export interface ServiceInfo {
  status: string;
  enabled: string;
}

export interface LogEntry {
  timestamp: string;
  level: string;
  message: string;
  component?: string;
}

export interface PAMServiceStatus {
  ID: string;
  Name: string;
  PAMFile: string;
  Status: string;
  ModulePath: string;
}

export interface AppConfig {
  inference: { address: string; timeout: number };
  camera: { device: string; ir_device: string; width: number; height: number; fps: number; pixel_format: string; auto_exposure: boolean };
  detection: { model_path: string; confidence: number; nms_threshold: number; input_size: number; max_detections: number };
  recognition: { similarity_threshold: number; enrollment_samples: number };
  liveness: { enabled: boolean; confidence_threshold: number };
  auth: { max_attempts: number; lockout_duration: number; fallback_enabled: boolean };
  challenge: { enabled: boolean; challenge_types: string[]; max_challenges: number; timeout: number };
  lockout: { enabled: boolean; max_failures: number; lockout_duration: number; progressive_lockout: boolean };
  storage: { data_dir: string; database_path: string };
  logging: { level: string };
}

export function CancelEnrollment(): Promise<void>;
export function ControlService(action: string): Promise<string>;
export function DeleteUser(username: string): Promise<void>;
export function DownloadLogs(): Promise<string>;
export function GetConfig(): Promise<AppConfig>;
export function GetEnrollmentStatus(): Promise<EnrollmentStatus>;
export function GetLogs(count: number): Promise<LogEntry[]>;
export function GetPAMServices(): Promise<PAMServiceStatus[]>;
export function GetPAMStatus(): Promise<string>;
export function GetServiceStatus(): Promise<ServiceInfo>;
export function GetUsers(): Promise<UserResponse[]>;
export function PAMAction(action: string, service: string): Promise<string>;
export function PAMToggle(enable: boolean): Promise<string>;
export function RunAuthTest(): Promise<AuthTestResult>;
export function SaveConfig(cfg: AppConfig): Promise<void>;
export function StartCamera(): Promise<void>;
export function StartCameraStream(): Promise<void>;
export function StartEnrollment(username: string): Promise<void>;
export function StopCamera(): Promise<void>;
export function StopCameraStream(): Promise<void>;
