// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {config} from '../models';

export function CancelEnrollment():Promise<void>;

export function CheckModels():Promise<main.ModelStatus>;

export function ControlService(arg1:string):Promise<string>;

export function DeleteUser(arg1:string):Promise<void>;

export function DownloadLogs():Promise<string>;

export function DownloadModels():Promise<void>;

export function GetConfig():Promise<config.Config>;

export function GetEnrollmentStatus():Promise<main.EnrollmentStatus>;

export function GetLogs(arg1:number):Promise<Array<main.LogEntry>>;

export function GetPAMServices():Promise<Array<main.PAMServiceStatus>>;

export function GetPAMStatus():Promise<string>;

export function GetServiceStatus():Promise<main.ServiceInfo>;

export function GetUsers():Promise<Array<main.UserResponse>>;

export function PAMAction(arg1:string,arg2:string):Promise<string>;

export function PAMToggle(arg1:boolean):Promise<string>;

export function RunAuthTest():Promise<main.AuthTestResult>;

export function SaveConfig(arg1:config.Config):Promise<void>;

export function StartCamera():Promise<void>;

export function StartCameraStream():Promise<void>;

export function StartEnrollment(arg1:string):Promise<void>;

export function StopCamera():Promise<void>;

export function StopCameraStream():Promise<void>;
