// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.19.6
// source: api/inference.proto

package inference

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FaceInference_DetectFaces_FullMethodName      = "/facelock.inference.FaceInference/DetectFaces"
	FaceInference_ExtractEmbedding_FullMethodName = "/facelock.inference.FaceInference/ExtractEmbedding"
	FaceInference_CheckLiveness_FullMethodName    = "/facelock.inference.FaceInference/CheckLiveness"
	FaceInference_Health_FullMethodName           = "/facelock.inference.FaceInference/Health"
)

// FaceInferenceClient is the client API for FaceInference service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Face detection and recognition inference service
type FaceInferenceClient interface {
	// Detect faces in an image and return bounding boxes with landmarks
	DetectFaces(ctx context.Context, in *DetectRequest, opts ...grpc.CallOption) (*DetectResponse, error)
	// Extract face embedding from aligned face image
	ExtractEmbedding(ctx context.Context, in *EmbeddingRequest, opts ...grpc.CallOption) (*EmbeddingResponse, error)
	// Check if face is real (liveness detection)
	CheckLiveness(ctx context.Context, in *LivenessRequest, opts ...grpc.CallOption) (*LivenessResponse, error)
	// Health check
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type faceInferenceClient struct {
	cc grpc.ClientConnInterface
}

func NewFaceInferenceClient(cc grpc.ClientConnInterface) FaceInferenceClient {
	return &faceInferenceClient{cc}
}

func (c *faceInferenceClient) DetectFaces(ctx context.Context, in *DetectRequest, opts ...grpc.CallOption) (*DetectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DetectResponse)
	err := c.cc.Invoke(ctx, FaceInference_DetectFaces_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *faceInferenceClient) ExtractEmbedding(ctx context.Context, in *EmbeddingRequest, opts ...grpc.CallOption) (*EmbeddingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmbeddingResponse)
	err := c.cc.Invoke(ctx, FaceInference_ExtractEmbedding_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *faceInferenceClient) CheckLiveness(ctx context.Context, in *LivenessRequest, opts ...grpc.CallOption) (*LivenessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LivenessResponse)
	err := c.cc.Invoke(ctx, FaceInference_CheckLiveness_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *faceInferenceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, FaceInference_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FaceInferenceServer is the server API for FaceInference service.
// All implementations must embed UnimplementedFaceInferenceServer
// for forward compatibility.
//
// Face detection and recognition inference service
type FaceInferenceServer interface {
	// Detect faces in an image and return bounding boxes with landmarks
	DetectFaces(context.Context, *DetectRequest) (*DetectResponse, error)
	// Extract face embedding from aligned face image
	ExtractEmbedding(context.Context, *EmbeddingRequest) (*EmbeddingResponse, error)
	// Check if face is real (liveness detection)
	CheckLiveness(context.Context, *LivenessRequest) (*LivenessResponse, error)
	// Health check
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedFaceInferenceServer()
}

// UnimplementedFaceInferenceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFaceInferenceServer struct{}

func (UnimplementedFaceInferenceServer) DetectFaces(context.Context, *DetectRequest) (*DetectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DetectFaces not implemented")
}
func (UnimplementedFaceInferenceServer) ExtractEmbedding(context.Context, *EmbeddingRequest) (*EmbeddingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExtractEmbedding not implemented")
}
func (UnimplementedFaceInferenceServer) CheckLiveness(context.Context, *LivenessRequest) (*LivenessResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckLiveness not implemented")
}
func (UnimplementedFaceInferenceServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedFaceInferenceServer) mustEmbedUnimplementedFaceInferenceServer() {}
func (UnimplementedFaceInferenceServer) testEmbeddedByValue()                       {}

// UnsafeFaceInferenceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FaceInferenceServer will
// result in compilation errors.
type UnsafeFaceInferenceServer interface {
	mustEmbedUnimplementedFaceInferenceServer()
}

func RegisterFaceInferenceServer(s grpc.ServiceRegistrar, srv FaceInferenceServer) {
	// If the following call panics, it indicates UnimplementedFaceInferenceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FaceInference_ServiceDesc, srv)
}

func _FaceInference_DetectFaces_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DetectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FaceInferenceServer).DetectFaces(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FaceInference_DetectFaces_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FaceInferenceServer).DetectFaces(ctx, req.(*DetectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FaceInference_ExtractEmbedding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmbeddingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FaceInferenceServer).ExtractEmbedding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FaceInference_ExtractEmbedding_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FaceInferenceServer).ExtractEmbedding(ctx, req.(*EmbeddingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FaceInference_CheckLiveness_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LivenessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FaceInferenceServer).CheckLiveness(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FaceInference_CheckLiveness_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FaceInferenceServer).CheckLiveness(ctx, req.(*LivenessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FaceInference_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FaceInferenceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FaceInference_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FaceInferenceServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FaceInference_ServiceDesc is the grpc.ServiceDesc for FaceInference service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FaceInference_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "facelock.inference.FaceInference",
	HandlerType: (*FaceInferenceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DetectFaces",
			Handler:    _FaceInference_DetectFaces_Handler,
		},
		{
			MethodName: "ExtractEmbedding",
			Handler:    _FaceInference_ExtractEmbedding_Handler,
		},
		{
			MethodName: "CheckLiveness",
			Handler:    _FaceInference_CheckLiveness_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _FaceInference_Health_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/inference.proto",
}
