// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: api/inference.proto

package inference

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Image data in raw format
type Image struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`          // Raw image bytes (JPEG/PNG) or raw pixel data
	Width         int32                  `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`       // Image width
	Height        int32                  `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`     // Image height
	Channels      int32                  `protobuf:"varint,4,opt,name=channels,proto3" json:"channels,omitempty"` // Number of channels (1=grayscale, 3=RGB)
	Format        string                 `protobuf:"bytes,5,opt,name=format,proto3" json:"format,omitempty"`      // Format: "jpeg", "png", "raw"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Image) Reset() {
	*x = Image{}
	mi := &file_api_inference_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Image) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Image) ProtoMessage() {}

func (x *Image) ProtoReflect() protoreflect.Message {
	mi := &file_api_inference_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Image.ProtoReflect.Descriptor instead.
func (*Image) Descriptor() ([]byte, []int) {
	return file_api_inference_proto_rawDescGZIP(), []int{0}
}

func (x *Image) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Image) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Image) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *Image) GetChannels() int32 {
	if x != nil {
		return x.Channels
	}
	return 0
}

func (x *Image) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

// Face detection bounding box with landmarks
type Detection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X1            float32                `protobuf:"fixed32,1,opt,name=x1,proto3" json:"x1,omitempty"`                 // Top-left x coordinate
	Y1            float32                `protobuf:"fixed32,2,opt,name=y1,proto3" json:"y1,omitempty"`                 // Top-left y coordinate
	X2            float32                `protobuf:"fixed32,3,opt,name=x2,proto3" json:"x2,omitempty"`                 // Bottom-right x coordinate
	Y2            float32                `protobuf:"fixed32,4,opt,name=y2,proto3" json:"y2,omitempty"`                 // Bottom-right y coordinate
	Confidence    float32                `protobuf:"fixed32,5,opt,name=confidence,proto3" json:"confidence,omitempty"` // Detection confidence score
	Landmarks     []*Landmark            `protobuf:"bytes,6,rep,name=landmarks,proto3" json:"landmarks,omitempty"`     // 5-point facial landmarks
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Detection) Reset() {
	*x = Detection{}
	mi := &file_api_inference_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Detection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Detection) ProtoMessage() {}

func (x *Detection) ProtoReflect() protoreflect.Message {
	mi := &file_api_inference_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Detection.ProtoReflect.Descriptor instead.
func (*Detection) Descriptor() ([]byte, []int) {
	return file_api_inference_proto_rawDescGZIP(), []int{1}
}

func (x *Detection) GetX1() float32 {
	if x != nil {
		return x.X1
	}
	return 0
}

func (x *Detection) GetY1() float32 {
	if x != nil {
		return x.Y1
	}
	return 0
}

func (x *Detection) GetX2() float32 {
	if x != nil {
		return x.X2
	}
	return 0
}

func (x *Detection) GetY2() float32 {
	if x != nil {
		return x.Y2
	}
	return 0
}

func (x *Detection) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *Detection) GetLandmarks() []*Landmark {
	if x != nil {
		return x.Landmarks
	}
	return nil
}

// Facial landmark point
type Landmark struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float32                `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Landmark) Reset() {
	*x = Landmark{}
	mi := &file_api_inference_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Landmark) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Landmark) ProtoMessage() {}

func (x *Landmark) ProtoReflect() protoreflect.Message {
	mi := &file_api_inference_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Landmark.ProtoReflect.Descriptor instead.
func (*Landmark) Descriptor() ([]byte, []int) {
	return file_api_inference_proto_rawDescGZIP(), []int{2}
}

func (x *Landmark) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Landmark) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

// Face embedding vector
type Embedding struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []float32              `protobuf:"fixed32,1,rep,packed,name=values,proto3" json:"values,omitempty"` // 512-dimensional embedding vector
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Embedding) Reset() {
	*x = Embedding{}
	mi := &file_api_inference_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Embedding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Embedding) ProtoMessage() {}

func (x *Embedding) ProtoReflect() protoreflect.Message {
	mi := &file_api_inference_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Embedding.ProtoReflect.Descriptor instead.
func (*Embedding) Descriptor() ([]byte, []int) {
	return file_api_inference_proto_rawDescGZIP(), []int{3}
}

func (x *Embedding) GetValues() []float32 {
	if x != nil {
		return x.Values
	}
	return nil
}

// Detection request
type DetectRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Image               *Image                 `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	ConfidenceThreshold float32                `protobuf:"fixed32,2,opt,name=confidence_threshold,json=confidenceThreshold,proto3" json:"confidence_threshold,omitempty"` // Minimum confidence (default: 0.5)
	NmsThreshold        float32                `protobuf:"fixed32,3,opt,name=nms_threshold,json=nmsThreshold,proto3" json:"nms_threshold,omitempty"`                      // NMS threshold (default: 0.4)
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *DetectRequest) Reset() {
	*x = DetectRequest{}
	mi := &file_api_inference_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectRequest) ProtoMessage() {}

func (x *DetectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_inference_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectRequest.ProtoReflect.Descriptor instead.
func (*DetectRequest) Descriptor() ([]byte, []int) {
	return file_api_inference_proto_rawDescGZIP(), []int{4}
}

func (x *DetectRequest) GetImage() *Image {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *DetectRequest) GetConfidenceThreshold() float32 {
	if x != nil {
		return x.ConfidenceThreshold
	}
	return 0
}

func (x *DetectRequest) GetNmsThreshold() float32 {
	if x != nil {
		return x.NmsThreshold
	}
	return 0
}

// Detection response
type DetectResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Detections      []*Detection           `protobuf:"bytes,1,rep,name=detections,proto3" json:"detections,omitempty"`
	InferenceTimeMs int32                  `protobuf:"varint,2,opt,name=inference_time_ms,json=inferenceTimeMs,proto3" json:"inference_time_ms,omitempty"` // Inference time in milliseconds
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DetectResponse) Reset() {
	*x = DetectResponse{}
	mi := &file_api_inference_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectResponse) ProtoMessage() {}

func (x *DetectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_inference_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectResponse.ProtoReflect.Descriptor instead.
func (*DetectResponse) Descriptor() ([]byte, []int) {
	return file_api_inference_proto_rawDescGZIP(), []int{5}
}

func (x *DetectResponse) GetDetections() []*Detection {
	if x != nil {
		return x.Detections
	}
	return nil
}

func (x *DetectResponse) GetInferenceTimeMs() int32 {
	if x != nil {
		return x.InferenceTimeMs
	}
	return 0
}

// Embedding extraction request
type EmbeddingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Image         *Image                 `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"` // Full image
	Face          *Detection             `protobuf:"bytes,2,opt,name=face,proto3" json:"face,omitempty"`   // Face bounding box and landmarks
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbeddingRequest) Reset() {
	*x = EmbeddingRequest{}
	mi := &file_api_inference_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbeddingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbeddingRequest) ProtoMessage() {}

func (x *EmbeddingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_inference_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbeddingRequest.ProtoReflect.Descriptor instead.
func (*EmbeddingRequest) Descriptor() ([]byte, []int) {
	return file_api_inference_proto_rawDescGZIP(), []int{6}
}

func (x *EmbeddingRequest) GetImage() *Image {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *EmbeddingRequest) GetFace() *Detection {
	if x != nil {
		return x.Face
	}
	return nil
}

// Embedding extraction response
type EmbeddingResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Embedding       *Embedding             `protobuf:"bytes,1,opt,name=embedding,proto3" json:"embedding,omitempty"`
	InferenceTimeMs int32                  `protobuf:"varint,2,opt,name=inference_time_ms,json=inferenceTimeMs,proto3" json:"inference_time_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *EmbeddingResponse) Reset() {
	*x = EmbeddingResponse{}
	mi := &file_api_inference_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbeddingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbeddingResponse) ProtoMessage() {}

func (x *EmbeddingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_inference_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbeddingResponse.ProtoReflect.Descriptor instead.
func (*EmbeddingResponse) Descriptor() ([]byte, []int) {
	return file_api_inference_proto_rawDescGZIP(), []int{7}
}

func (x *EmbeddingResponse) GetEmbedding() *Embedding {
	if x != nil {
		return x.Embedding
	}
	return nil
}

func (x *EmbeddingResponse) GetInferenceTimeMs() int32 {
	if x != nil {
		return x.InferenceTimeMs
	}
	return 0
}

// Liveness detection request
type LivenessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Image         *Image                 `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	Face          *Detection             `protobuf:"bytes,2,opt,name=face,proto3" json:"face,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LivenessRequest) Reset() {
	*x = LivenessRequest{}
	mi := &file_api_inference_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LivenessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LivenessRequest) ProtoMessage() {}

func (x *LivenessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_inference_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LivenessRequest.ProtoReflect.Descriptor instead.
func (*LivenessRequest) Descriptor() ([]byte, []int) {
	return file_api_inference_proto_rawDescGZIP(), []int{8}
}

func (x *LivenessRequest) GetImage() *Image {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *LivenessRequest) GetFace() *Detection {
	if x != nil {
		return x.Face
	}
	return nil
}

// Liveness detection response
type LivenessResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	IsLive          bool                   `protobuf:"varint,1,opt,name=is_live,json=isLive,proto3" json:"is_live,omitempty"`
	Confidence      float32                `protobuf:"fixed32,2,opt,name=confidence,proto3" json:"confidence,omitempty"`
	InferenceTimeMs int32                  `protobuf:"varint,3,opt,name=inference_time_ms,json=inferenceTimeMs,proto3" json:"inference_time_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *LivenessResponse) Reset() {
	*x = LivenessResponse{}
	mi := &file_api_inference_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LivenessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LivenessResponse) ProtoMessage() {}

func (x *LivenessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_inference_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LivenessResponse.ProtoReflect.Descriptor instead.
func (*LivenessResponse) Descriptor() ([]byte, []int) {
	return file_api_inference_proto_rawDescGZIP(), []int{9}
}

func (x *LivenessResponse) GetIsLive() bool {
	if x != nil {
		return x.IsLive
	}
	return false
}

func (x *LivenessResponse) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *LivenessResponse) GetInferenceTimeMs() int32 {
	if x != nil {
		return x.InferenceTimeMs
	}
	return 0
}

// Health check request
type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_api_inference_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_inference_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_api_inference_proto_rawDescGZIP(), []int{10}
}

// Health check response
type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Device        string                 `protobuf:"bytes,3,opt,name=device,proto3" json:"device,omitempty"` // "cpu", "cuda", "rocm", "directml"
	ModelsLoaded  []string               `protobuf:"bytes,4,rep,name=models_loaded,json=modelsLoaded,proto3" json:"models_loaded,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_api_inference_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_inference_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_api_inference_proto_rawDescGZIP(), []int{11}
}

func (x *HealthResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthResponse) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *HealthResponse) GetModelsLoaded() []string {
	if x != nil {
		return x.ModelsLoaded
	}
	return nil
}

var File_api_inference_proto protoreflect.FileDescriptor

const file_api_inference_proto_rawDesc = "" +
	"\n" +
	"\x13api/inference.proto\x12\x12facelock.inference\"}\n" +
	"\x05Image\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x14\n" +
	"\x05width\x18\x02 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x03 \x01(\x05R\x06height\x12\x1a\n" +
	"\bchannels\x18\x04 \x01(\x05R\bchannels\x12\x16\n" +
	"\x06format\x18\x05 \x01(\tR\x06format\"\xa7\x01\n" +
	"\tDetection\x12\x0e\n" +
	"\x02x1\x18\x01 \x01(\x02R\x02x1\x12\x0e\n" +
	"\x02y1\x18\x02 \x01(\x02R\x02y1\x12\x0e\n" +
	"\x02x2\x18\x03 \x01(\x02R\x02x2\x12\x0e\n" +
	"\x02y2\x18\x04 \x01(\x02R\x02y2\x12\x1e\n" +
	"\n" +
	"confidence\x18\x05 \x01(\x02R\n" +
	"confidence\x12:\n" +
	"\tlandmarks\x18\x06 \x03(\v2\x1c.facelock.inference.LandmarkR\tlandmarks\"&\n" +
	"\bLandmark\x12\f\n" +
	"\x01x\x18\x01 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x02R\x01y\"#\n" +
	"\tEmbedding\x12\x16\n" +
	"\x06values\x18\x01 \x03(\x02R\x06values\"\x98\x01\n" +
	"\rDetectRequest\x12/\n" +
	"\x05image\x18\x01 \x01(\v2\x19.facelock.inference.ImageR\x05image\x121\n" +
	"\x14confidence_threshold\x18\x02 \x01(\x02R\x13confidenceThreshold\x12#\n" +
	"\rnms_threshold\x18\x03 \x01(\x02R\fnmsThreshold\"{\n" +
	"\x0eDetectResponse\x12=\n" +
	"\n" +
	"detections\x18\x01 \x03(\v2\x1d.facelock.inference.DetectionR\n" +
	"detections\x12*\n" +
	"\x11inference_time_ms\x18\x02 \x01(\x05R\x0finferenceTimeMs\"v\n" +
	"\x10EmbeddingRequest\x12/\n" +
	"\x05image\x18\x01 \x01(\v2\x19.facelock.inference.ImageR\x05image\x121\n" +
	"\x04face\x18\x02 \x01(\v2\x1d.facelock.inference.DetectionR\x04face\"|\n" +
	"\x11EmbeddingResponse\x12;\n" +
	"\tembedding\x18\x01 \x01(\v2\x1d.facelock.inference.EmbeddingR\tembedding\x12*\n" +
	"\x11inference_time_ms\x18\x02 \x01(\x05R\x0finferenceTimeMs\"u\n" +
	"\x0fLivenessRequest\x12/\n" +
	"\x05image\x18\x01 \x01(\v2\x19.facelock.inference.ImageR\x05image\x121\n" +
	"\x04face\x18\x02 \x01(\v2\x1d.facelock.inference.DetectionR\x04face\"w\n" +
	"\x10LivenessResponse\x12\x17\n" +
	"\ais_live\x18\x01 \x01(\bR\x06isLive\x12\x1e\n" +
	"\n" +
	"confidence\x18\x02 \x01(\x02R\n" +
	"confidence\x12*\n" +
	"\x11inference_time_ms\x18\x03 \x01(\x05R\x0finferenceTimeMs\"\x0f\n" +
	"\rHealthRequest\"\x81\x01\n" +
	"\x0eHealthResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x16\n" +
	"\x06device\x18\x03 \x01(\tR\x06device\x12#\n" +
	"\rmodels_loaded\x18\x04 \x03(\tR\fmodelsLoaded2\xf3\x02\n" +
	"\rFaceInference\x12T\n" +
	"\vDetectFaces\x12!.facelock.inference.DetectRequest\x1a\".facelock.inference.DetectResponse\x12_\n" +
	"\x10ExtractEmbedding\x12$.facelock.inference.EmbeddingRequest\x1a%.facelock.inference.EmbeddingResponse\x12Z\n" +
	"\rCheckLiveness\x12#.facelock.inference.LivenessRequest\x1a$.facelock.inference.LivenessResponse\x12O\n" +
	"\x06Health\x12!.facelock.inference.HealthRequest\x1a\".facelock.inference.HealthResponseB\x11Z\x0f./api;inferenceb\x06proto3"

var (
	file_api_inference_proto_rawDescOnce sync.Once
	file_api_inference_proto_rawDescData []byte
)

func file_api_inference_proto_rawDescGZIP() []byte {
	file_api_inference_proto_rawDescOnce.Do(func() {
		file_api_inference_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_inference_proto_rawDesc), len(file_api_inference_proto_rawDesc)))
	})
	return file_api_inference_proto_rawDescData
}

var file_api_inference_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_api_inference_proto_goTypes = []any{
	(*Image)(nil),             // 0: facelock.inference.Image
	(*Detection)(nil),         // 1: facelock.inference.Detection
	(*Landmark)(nil),          // 2: facelock.inference.Landmark
	(*Embedding)(nil),         // 3: facelock.inference.Embedding
	(*DetectRequest)(nil),     // 4: facelock.inference.DetectRequest
	(*DetectResponse)(nil),    // 5: facelock.inference.DetectResponse
	(*EmbeddingRequest)(nil),  // 6: facelock.inference.EmbeddingRequest
	(*EmbeddingResponse)(nil), // 7: facelock.inference.EmbeddingResponse
	(*LivenessRequest)(nil),   // 8: facelock.inference.LivenessRequest
	(*LivenessResponse)(nil),  // 9: facelock.inference.LivenessResponse
	(*HealthRequest)(nil),     // 10: facelock.inference.HealthRequest
	(*HealthResponse)(nil),    // 11: facelock.inference.HealthResponse
}
var file_api_inference_proto_depIdxs = []int32{
	2,  // 0: facelock.inference.Detection.landmarks:type_name -> facelock.inference.Landmark
	0,  // 1: facelock.inference.DetectRequest.image:type_name -> facelock.inference.Image
	1,  // 2: facelock.inference.DetectResponse.detections:type_name -> facelock.inference.Detection
	0,  // 3: facelock.inference.EmbeddingRequest.image:type_name -> facelock.inference.Image
	1,  // 4: facelock.inference.EmbeddingRequest.face:type_name -> facelock.inference.Detection
	3,  // 5: facelock.inference.EmbeddingResponse.embedding:type_name -> facelock.inference.Embedding
	0,  // 6: facelock.inference.LivenessRequest.image:type_name -> facelock.inference.Image
	1,  // 7: facelock.inference.LivenessRequest.face:type_name -> facelock.inference.Detection
	4,  // 8: facelock.inference.FaceInference.DetectFaces:input_type -> facelock.inference.DetectRequest
	6,  // 9: facelock.inference.FaceInference.ExtractEmbedding:input_type -> facelock.inference.EmbeddingRequest
	8,  // 10: facelock.inference.FaceInference.CheckLiveness:input_type -> facelock.inference.LivenessRequest
	10, // 11: facelock.inference.FaceInference.Health:input_type -> facelock.inference.HealthRequest
	5,  // 12: facelock.inference.FaceInference.DetectFaces:output_type -> facelock.inference.DetectResponse
	7,  // 13: facelock.inference.FaceInference.ExtractEmbedding:output_type -> facelock.inference.EmbeddingResponse
	9,  // 14: facelock.inference.FaceInference.CheckLiveness:output_type -> facelock.inference.LivenessResponse
	11, // 15: facelock.inference.FaceInference.Health:output_type -> facelock.inference.HealthResponse
	12, // [12:16] is the sub-list for method output_type
	8,  // [8:12] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_api_inference_proto_init() }
func file_api_inference_proto_init() {
	if File_api_inference_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_inference_proto_rawDesc), len(file_api_inference_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_inference_proto_goTypes,
		DependencyIndexes: file_api_inference_proto_depIdxs,
		MessageInfos:      file_api_inference_proto_msgTypes,
	}.Build()
	File_api_inference_proto = out.File
	file_api_inference_proto_goTypes = nil
	file_api_inference_proto_depIdxs = nil
}
